### ISSUE TITLE
BlendingToolKit paper sprint

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/SprintWeek2022#10]
# BTK Paper Sprint

![Readiness](https://img.shields.io/badge/Sprint%20Readiness-Perfect-gold?style=for-the-badge) 

We will be working through the code-release paper of the Blending ToolKit, a toolkit for producing images of galaxy blends and evaluating deblender performance. You can learn about BTK by taking a look at the [documentation](https://lsstdesc.org/BlendingToolKit/index.html).

Contacts: @ismael-mendoza, @mpaillassa 
Time: Mornings ET
Main communication channel: [#blending_toolkit ](https://lsstc.slack.com/archives/CBXM2G6MP)
GitHub repo: https://github.com/LSSTDESC/BlendingToolKit
In-person/Virtual/Hybrid: **Hybrid**
Zoom room (if applicable): [link](https://umich.zoom.us/j/91640257620?pwd=SDRFM2JQSEFZcngzUjhoakRIOG9UZz09)

## Goals and deliverable

Not all of the following must be completed but I would like to give people an option to work on different things

- [ ] Review [rotation](https://github.com/LSSTDESC/BlendingToolKit/commit/1d862ee2481b482d723aba30d52dac2836f77ba7) and [shear](https://github.com/LSSTDESC/BlendingToolKit/pull/381) PRs/commits
- [ ] Add mention to paper about shear and data augmentation (rotation).
- [ ] Decide on figures missing from this [list](https://github.com/LSSTDESC/BlendingToolKit/issues/375)
- [ ] Clear placeholders for figures in overleaf, including captions if possible and in-text descirption.
- [ ] Implement aperture photometry as a metric ([PR](https://github.com/LSSTDESC/BlendingToolKit/issues/342))
- [ ] Write unit-test to ensure galaxies are shifted correctly ([PR](https://github.com/LSSTDESC/BlendingToolKit/issues/318))
- [ ] Overall resolution of Axel/Maxime/Ismael/Alex's comments in overleaf 
- [ ] Rewrite parts of intro so to emphasize the unique contribution of BTK "galsim provides sims, but no package explicitly devoted to understanding the blending problem"
- [ ] Expand intro to make it less WL focused.
- [ ] Go through paper and remove any "code-specific" mentions (anything that uses `\texttt{}`) and replace with high-level/intuition.
- [ ] Give one or two sentence intuition of some of the reconstruction metrics

## Resources and skills needed

Anyone with interest in blending is welcome to join! We definitely want as much feedback on the manuscript as possible :-) 

For anyone new to BTK and interested in learning more, we have a set of [tutorials](https://github.com/LSSTDESC/BlendingToolKit/tree/main/notebooks). You can run them by clicking on the `binder` badge in the BTK main github [page](https://github.com/LSSTDESC/BlendingToolKit). I am happy to talk through any of them and answer any questions during the sprint week. 

For a newcomer, a natural goal for the sprint week might be adding functionality to produce one of the figures in the paper. Reviewing a specific part of the paper is also an option. I would be happy to help you figure out a concrete task that matches your interests.

## Detailed description

The overleaf can be found [here](https://www.overleaf.com/read/vwsqkmgmqvpt).

This paper will serve as a code-release paper of the BlendingToolkit and will describe its core functionality, API, how blend simulations are produced, available deblenders, and available metrics. It will also demonstrate how the output of BTK can aid future blending studies by demonstrating comparison metrics between deblenders currently found within BTK.
